# JDBC PROPERTIES
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springstkpush-db?useSSL=false
    username: root
    password: rootUser@123
    drive-class-name: mysql.cj.jdbc.Driver
  application:
    name: springstkpush
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql