spring:
  datasource:
    url:
    username:
    password:
    drive-class-name: mysql.cj.jdbc.Driver
  application:
    name: springstkpush
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  # SET ACTIVE PROFILE TO THE DEV ENV
  profiles:
    active: dev

# DARAJA API SPECIFICS
mpesa:
  consumer:
    key:
    secret:
  business:
    shortcode:
  public:
    passkey:
  callback:
    urlbase: 